# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 13:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeystData',
            fields=[
                ('field_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('field_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keystdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
